# Lesson 5    22 Aug 2018

In [10]:
import numpy as np
from datascience import *

1)

In [4]:
Data = make_array(['John','Wirth','OK','Blue'])
Data

array([['John', 'Wirth', 'OK', 'Blue']], dtype='<U5')

1 a)

In [16]:
UData = np.char.upper(Data)
UData

array([['JOHN', 'WIRTH', 'OK', 'BLUE']], dtype='<U5')

SyntaxError: invalid syntax (<ipython-input-20-b5a3c09460f9>, line 1)

1 b)

In [22]:
np.char.count(Data,'a')

array([[0, 0, 0, 0]])

2)

In [24]:
odds = np.arange(1.,42,4)
odds

array([ 1.,  5.,  9., 13., 17., 21., 25., 29., 33., 37., 41.])

2 a)

In [26]:
Sum = np.sum(odds)
Sum

231.0

In [27]:
np.prod(odds)

7579867420125.0

We can also do this with the astype method.

In [36]:
odds32=np.arange(1,42,4)
odds32

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41])

In [30]:
odds321 = odds32.astype('float')
odds321

array([ 1.,  5.,  9., 13., 17., 21., 25., 29., 33., 37., 41.])

Note: np.prod(ARRAY) is a function
      ARRAY.astype(TYPE) is a method

2 b)

In [31]:
np.log(odds)

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207])

In [37]:
np.log(odds32)

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207])

2 c)